name: simple-voting

services:
  appserver:
    type: php:8.2
    via: apache
    webroot: web
    xdebug: false
    overrides:
      environment:
        PHP_MEMORY_LIMIT: 512M

  database:
    type: mariadb:10.6
    portforward: true
    creds:
      database: drupal
      user: drupal
      password: drupal

tooling:
  composer:
    service: appserver
  php:
    service: appserver
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
